from sqlalchemy import Column, String, Integer, Boolean, JSON, Numeric, DateTime, ForeignKey, UniqueConstraint, CheckConstraint
from sqlalchemy.orm import relationship
from app.models.base import BaseModel


class StrategyConfiguration(BaseModel):
    """
    Normalized Strategy Configuration entity representing a unique parameter set for a strategy type on an instrument.
    """
    __tablename__ = "strategy_configurations"
    __table_args__ = (
        UniqueConstraint(
            "instrument_id",
            "strategy_type",
            "configuration_hash",
            name="uq_strategy_config_inst_type_hash"
        ),
        {"schema": "strategy"}
    )

    strategy_type = Column(String(64), nullable=False, default="MOVING_AVERAGE")
    instrument_id = Column(String(36), ForeignKey("core.instruments.id", ondelete="CASCADE"), nullable=False, index=True)
    configuration_hash = Column(String(64), nullable=False, index=True)
    ma_type = Column(String(16), nullable=True)
    fast_window = Column(Integer, nullable=True)
    slow_window = Column(Integer, nullable=True)
    price_source = Column(String(32), nullable=True)
    configuration_json = Column(JSON, nullable=False)
    active = Column(Boolean, nullable=False, default=True)

    signals = relationship("SignalEvent", back_populates="configuration", cascade="all, delete-orphan")


class SignalEvent(BaseModel):
    """
    Standardized Signal Event generated by quantitative strategy engines.
    """
    __tablename__ = "signal_events"
    __table_args__ = (
        UniqueConstraint(
            "strategy_configuration_id",
            "timestamp",
            "signal_type",
            name="uq_signal_events_config_ts_type"
        ),
        CheckConstraint("price >= 0", name="ck_signal_events_price_nonnegative"),
        {"schema": "strategy"}
    )

    strategy_configuration_id = Column(
        String(36),
        ForeignKey("strategy.strategy_configurations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    instrument_id = Column(
        String(36),
        ForeignKey("core.instruments.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    signal_type = Column(String(16), nullable=False, index=True)
    signal_state = Column(String(16), nullable=False)
    price = Column(Numeric(18, 8), nullable=False)
    source = Column(String(32), nullable=False, default="STRATEGY_ENGINE")
    metadata_json = Column("metadata", JSON, nullable=True)

    configuration = relationship("StrategyConfiguration", back_populates="signals")
